### PR TITLE
 Enable joystick support 

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by LeandroStanger** [comment]
bot, build

**Comment by hfiguiere** [comment]
If game controllers needs to be used, this is the right fix.

**Comment by son-link** [comment]
The game does not support gamepads/joystick, I have looked around the forums and in the Wiki, unless you use some program to map the buttons, d-pad, etc, as if they were keyboard and mouse keys, like QJoyPad.

**Pull request closed without merging**
