### PR TITLE
Update to 4.0.0

### PR DESCRIPTION
**Pull request by Elinvention**

### CODE REVIEW

**Comment by EchedelleLR** [comment]
Any update into this?

**Comment by EchedelleLR** [comment]
Seems DNS issue.

```
Cloning into 'vulkan_headers-src'...
fatal: unable to access 'https://github.com/KhronosGroup/Vulkan-Headers.git/': Could not resolve host: github.com
Cloning into 'vulkan_headers-src'...
fatal: unable to access 'https://github.com/KhronosGroup/Vulkan-Headers.git/': Could not resolve host: github.com
Cloning into 'vulkan_headers-src'...
fatal: unable to access 'https://github.com/KhronosGroup/Vulkan-Headers.git/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at vulkan_headers-subbuild/vulkan_headers-populate-prefix/tmp/vulkan_headers-populate-gitclone.cmake:31 (message):
  Failed to clone repository:
  'https://github.com/KhronosGroup/Vulkan-Headers.git'
```

**Comment by EchedeyLR** [comment]
@flathubbot help

**Comment by Elinvention** [comment]
bot, build

**Comment by EchedelleLR** [comment]
Issue still present. 

```
Cloning into 'vulkan_headers-src'...
fatal: unable to access 'https://github.com/KhronosGroup/Vulkan-Headers.git/': Could not resolve host: github.com
Cloning into 'vulkan_headers-src'...
fatal: unable to access 'https://github.com/KhronosGroup/Vulkan-Headers.git/': Could not resolve host: github.com
Cloning into 'vulkan_headers-src'...
fatal: unable to access 'https://github.com/KhronosGroup/Vulkan-Headers.git/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at vulkan_headers-subbuild/vulkan_headers-populate-prefix/tmp/vulkan_headers-populate-gitclone.cmake:31 (message):
  Failed to clone repository:
  'https://github.com/KhronosGroup/Vulkan-Headers.git'
```

Could it be a problem in the bot itself?

**Comment by Elinvention** [comment]
I think so, it looks like the bot is unable to resolve github.com at the moment. But I'm no expert, so it could be something else.

**Comment by Elinvention** [comment]
bot, build

**Comment by past-due** [comment]
Strange that it can't access github.com.

Adding `-DWZ_ENABLE_BACKEND_VULKAN=OFF` to the `config-opts:` will bypass this, but will also compile WZ without the Vulkan backend. (Leaving just the typical OpenGL / OpenGL ES support.)

That might be a good workaround for now, as I'm not sure if additional tweaks are required to get Vulkan to work with the Flatpak? (Certainly it'll also need `glslc` / the Vulkan SDK as a built-time dependency.)

**Comment by AsciiWolf** [comment]
@past-due Not strange. Flatpak-builder has network access disabled on purpose.

```-- Could NOT find VulkanHeaders: Found unsuitable version "114", but required is at least "148" (found /usr/include)```

You can try adding the latest stable Vulkan headers as a module or submitting a ticket to the KDE runtime.

Disabling the Vulkan renderer is not a good solution.

**Comment by Elinvention** [comment]
@AsciiWolf thanks to your comment I realized that the error was happening in the build phase and that we are using an outdated kde runtime.

**Comment by Elinvention** [comment]
The build works, but without Vulkan backend:
```
GLSLC shader compiler not found - disabling Vulkan backend
```
The issue here is that the Freedesktop runtime added GLSLC in [this commit](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/4734a84c5b06be98e6faeead9d7aee7bd134bfdc), however freedesktop version 20.08 does not yet include that commit.
We can wait for a new version of the runtime, or include it ourselves.

**Comment by past-due** [comment]
> The issue here is that the Freedesktop runtime added GLSLC in [this commit](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/4734a84c5b06be98e6faeead9d7aee7bd134bfdc), however freedesktop version 20.08 does not yet include that commit.
> We can wait for a new version of the runtime, or include it ourselves.

Do you know how long it might take for a new version of the runtime to drop?

Building shaderc manually would just require something like:
```sh
  mkdir tmp_shaderc_build
  cd "tmp_shaderc_build"

  # glslc build dependencies
  # TODO: install cmake python3 lcov

  # glslc - clone
  echo "Fetching shaderc"
  git clone https://github.com/google/shaderc shaderc
  cd shaderc
  git checkout tags/v2020.4 -b v2020.4
  ./utils/git-sync-deps
  cd ..

  # glslc - cmake build + install
  mkdir shaderc_build
  cd shaderc_build
  echo "Configuring shaderc"
  cmake -GNinja -DSHADERC_SKIP_TESTS=ON -DCMAKE_BUILD_TYPE=Release ../shaderc/
  echo "Compiling shaderc"
  cmake --build . --target install
  cd ..

  cd ..
  rm -rf "tmp_shaderc_build"
```

And then potentially uninstalling it / removing it as part of cleanup, since it's only needed at build-time?

**Comment by EchedelleLR** [comment]
I have no issues to wait for the vulkan backend. Most graphics cards are not supported and mine is included in that so I have no issues with it.

This game can run even in Intel Celeron 3rd Generation of Intel HD Graphics.

Just release it "as is" right now.

**Pull request merged**
